CREATE SCHEMA IF NOT EXISTS intake_normalizer;

CREATE TABLE IF NOT EXISTS intake_normalizer.batches (
  batch_id UUID PRIMARY KEY,
  batch_label TEXT,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total_rows INTEGER NOT NULL,
  missing_applicant_id INTEGER NOT NULL,
  missing_name INTEGER NOT NULL,
  missing_email INTEGER NOT NULL,
  invalid_email INTEGER NOT NULL,
  missing_phone INTEGER NOT NULL DEFAULT 0,
  invalid_phone INTEGER NOT NULL DEFAULT 0,
  missing_program INTEGER NOT NULL,
  missing_school_type INTEGER NOT NULL DEFAULT 0,
  missing_referral_source INTEGER NOT NULL DEFAULT 0,
  missing_income INTEGER NOT NULL,
  missing_citizenship_status INTEGER NOT NULL DEFAULT 0,
  unrecognized_citizenship_status INTEGER NOT NULL DEFAULT 0,
  low_gpa INTEGER NOT NULL,
  invalid_gpa INTEGER NOT NULL,
  gpa_out_of_range INTEGER NOT NULL,
  first_gen INTEGER NOT NULL,
  first_gen_rate NUMERIC(5, 2),
  invalid_submission_date INTEGER NOT NULL,
  future_submission_date INTEGER NOT NULL,
  missing_submission_date INTEGER NOT NULL DEFAULT 0,
  stale_submission INTEGER NOT NULL DEFAULT 0,
  missing_graduation_year INTEGER NOT NULL DEFAULT 0,
  invalid_graduation_year INTEGER NOT NULL DEFAULT 0,
  graduation_year_out_of_range INTEGER NOT NULL DEFAULT 0,
  duplicate_email INTEGER NOT NULL,
  duplicate_applicant_id INTEGER NOT NULL,
  duplicate_phone INTEGER NOT NULL DEFAULT 0,
  flagged_applications INTEGER NOT NULL,
  flagged_rate NUMERIC(5, 2) NOT NULL,
  gpa_avg NUMERIC(4, 2),
  gpa_min NUMERIC(4, 2),
  gpa_max NUMERIC(4, 2),
  submission_start DATE,
  submission_end DATE,
  program_counts JSONB NOT NULL,
  program_gpa_avg JSONB NOT NULL,
  first_gen_program_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  first_gen_program_rates JSONB NOT NULL DEFAULT '{}'::jsonb,
  school_type_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  referral_source_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  income_bracket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  citizenship_status_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  note_tag_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  email_domain_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  email_domain_category_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  phone_country_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  contact_channel_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  submission_weekday_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  review_status_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  review_priority_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  flag_severity_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  data_quality_avg NUMERIC(5, 2),
  data_quality_min INTEGER,
  data_quality_max INTEGER,
  quality_tier_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  readiness_avg NUMERIC(5, 2),
  readiness_min INTEGER,
  readiness_max INTEGER,
  readiness_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  submission_age_avg NUMERIC(6, 2),
  submission_age_min INTEGER,
  submission_age_max INTEGER,
  submission_age_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  submission_recency_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  graduation_year_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  graduation_year_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS intake_normalizer.applications (
  application_id BIGSERIAL PRIMARY KEY,
  batch_id UUID NOT NULL REFERENCES intake_normalizer.batches(batch_id) ON DELETE CASCADE,
  applicant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  phone_normalized TEXT,
  phone_country TEXT,
  contact_channel TEXT,
  program TEXT NOT NULL,
  referral_source TEXT,
  gpa NUMERIC(4, 2),
  income_bracket TEXT,
  submission_date DATE,
  submission_age_days INTEGER,
  submission_age_bucket TEXT,
  submission_recency TEXT NOT NULL DEFAULT 'missing',
  graduation_year INTEGER,
  graduation_year_bucket TEXT NOT NULL DEFAULT 'unknown',
  first_gen BOOLEAN NOT NULL DEFAULT FALSE,
  email_domain_category TEXT NOT NULL DEFAULT 'missing',
  eligibility_notes TEXT,
  note_tags TEXT[] NOT NULL DEFAULT '{}',
  school_type TEXT,
  citizenship_status TEXT,
  flags TEXT[] NOT NULL,
  flag_severity TEXT NOT NULL DEFAULT 'clean',
  review_status TEXT NOT NULL DEFAULT 'ready',
  review_priority TEXT NOT NULL DEFAULT 'ready',
  data_quality_score INTEGER NOT NULL DEFAULT 100,
  readiness_score INTEGER NOT NULL DEFAULT 100,
  readiness_bucket TEXT NOT NULL DEFAULT 'ready'
);


ALTER TABLE intake_normalizer.batches
  ADD COLUMN IF NOT EXISTS missing_program INTEGER NOT NULL DEFAULT 0;

ALTER TABLE intake_normalizer.batches
  ADD COLUMN IF NOT EXISTS gpa_out_of_range INTEGER NOT NULL DEFAULT 0;

ALTER TABLE intake_normalizer.batches
  ADD COLUMN IF NOT EXISTS missing_referral_source INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missing_school_type INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missing_citizenship_status INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unrecognized_citizenship_status INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missing_name INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duplicate_applicant_id INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duplicate_phone INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flagged_applications INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flagged_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gpa_avg NUMERIC(4, 2),
  ADD COLUMN IF NOT EXISTS gpa_min NUMERIC(4, 2),
  ADD COLUMN IF NOT EXISTS gpa_max NUMERIC(4, 2),
  ADD COLUMN IF NOT EXISTS first_gen_rate NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS program_gpa_avg JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS first_gen_program_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS first_gen_program_rates JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS school_type_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS referral_source_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS income_bracket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS citizenship_status_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS note_tag_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS email_domain_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS email_domain_category_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS missing_phone INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invalid_phone INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS phone_country_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS contact_channel_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS submission_weekday_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS review_status_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS review_priority_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS flag_severity_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS data_quality_avg NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS data_quality_min INTEGER,
  ADD COLUMN IF NOT EXISTS data_quality_max INTEGER,
  ADD COLUMN IF NOT EXISTS quality_tier_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS readiness_avg NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS readiness_min INTEGER,
  ADD COLUMN IF NOT EXISTS readiness_max INTEGER,
  ADD COLUMN IF NOT EXISTS readiness_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS missing_submission_date INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stale_submission INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missing_graduation_year INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invalid_graduation_year INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS graduation_year_out_of_range INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS submission_age_avg NUMERIC(6, 2),
  ADD COLUMN IF NOT EXISTS submission_age_min INTEGER,
  ADD COLUMN IF NOT EXISTS submission_age_max INTEGER,
  ADD COLUMN IF NOT EXISTS submission_age_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS submission_recency_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS graduation_year_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS graduation_year_bucket_counts JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE intake_normalizer.applications
  ADD COLUMN IF NOT EXISTS note_tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS referral_source TEXT,
  ADD COLUMN IF NOT EXISTS school_type TEXT,
  ADD COLUMN IF NOT EXISTS citizenship_status TEXT,
  ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS review_priority TEXT NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS data_quality_score INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS readiness_score INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS readiness_bucket TEXT NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS flag_severity TEXT NOT NULL DEFAULT 'clean',
  ADD COLUMN IF NOT EXISTS submission_age_days INTEGER,
  ADD COLUMN IF NOT EXISTS submission_age_bucket TEXT,
  ADD COLUMN IF NOT EXISTS submission_recency TEXT NOT NULL DEFAULT 'missing',
  ADD COLUMN IF NOT EXISTS graduation_year INTEGER,
  ADD COLUMN IF NOT EXISTS graduation_year_bucket TEXT NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS email_domain_category TEXT NOT NULL DEFAULT 'missing',
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS phone_normalized TEXT,
  ADD COLUMN IF NOT EXISTS phone_country TEXT,
  ADD COLUMN IF NOT EXISTS contact_channel TEXT;

CREATE INDEX IF NOT EXISTS idx_intake_normalizer_program
  ON intake_normalizer.applications(program);
